POST http://localhost:5000/api/register
Content-Type: application/json

{
    "email": "testuser@gmail.com",
    "password": "testpassword"
}

####

POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "riyakadamvpp@gmail.com",
    "password": "riya1313"
}

####

GET http://localhost:5000/api/memelist
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY0YjI5MTBlZjQwMThhNGVmN2QyNzkyIiwiZW1haWwiOiJyaXlha2FkYW12cHBAZ21haWwuY29tIn0sImlhdCI6MTcxNjgwOTIzOSwiZXhwIjoxNzE3MDI1MjM5fQ.tVsogNurtruUyq3xiccBRZsaI-nv7Noyof-fE-BMt74

####
GET http://localhost:5000/api/user/peeps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY0YjI5MTBlZjQwMThhNGVmN2QyNzkyIiwiZW1haWwiOiJyaXlha2FkYW12cHBAZ21haWwuY29tIn0sImlhdCI6MTcxNjgwOTIzOSwiZXhwIjoxNzE3MDI1MjM5fQ.tVsogNurtruUyq3xiccBRZsaI-nv7Noyof-fE-BMt74
