POST http://localhost:5000/api/register
Content-Type: application/json

{
    "email": "testuser@gmail.com",
    "password": "testpassword"
}

####

POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "Swaraj.m@somaiya.edu",
    "password": "12345678"
}

####

GET http://localhost:5000/api/memelist
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY0YjM3ZGRlZjQwMThhNGVmN2QyODJiIiwiZW1haWwiOiJTd2FyYWoubUBzb21haXlhLmVkdSJ9LCJpYXQiOjE3MTYyMDc1MjIsImV4cCI6MTcxNjQyMzUyMn0.rDSDg-MRBZMm87FDCcY8_ZZq615_CPp9vDv5bauDab8

